spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/hotelcali
    username: postgres
    password: W3lcome22209
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true